# Generated by Django 4.1 on 2024-08-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('locationid', models.IntegerField(primary_key=True, serialize=False)),
                ('applicant', models.TextField(blank=True, null=True)),
                ('facility_type', models.TextField(blank=True, null=True)),
                ('location_description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('permit', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
