# Generated by Django 5.1 on 2024-08-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='foodItems',
            field=models.TextField(blank=True, null=True),
        ),
    ]
